### PR TITLE
Added Javaslang, a functional library for Java 8

### PR DESCRIPTION
**Pull request by danieldietrich**
Hi,
this makes functional programming in Java 8 more comfortable.
Greets
Daniel

### CODE REVIEW

**Comment by cxxr** [comment]
Javaslang looks great, but the copy you wrote doesn't fit the tone of the rest of the article. Could you make it use less personal pronouns and more informative?

"Ever want to do X in Java? Well, with Javaslang it's as easy as Y. It also does Z."

**Comment by danieldietrich** [comment]
Of cause. Did I write that? Will fix it soon...

**Comment by danieldietrich** [comment]
@cxxr Please let me know if something is missing.

**Comment by danieldietrich** [comment]
@cxxr Please review my changes. I would really appreciate a pull. Thanks, Daniel

**Pull request merged**
